---
- hosts: master
  become: True
  tasks:
    - name: Disable Selinux
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      notify: reboot selinux
    - name: Rebooting SELinux
      meta: flush_handlers
    
    - name: Ensure Apache is installed
      include: apache.yml
    
    - name: Ensure PHPFPM is installed
      include: phpfpm.yml

    - name: Install Zabbix Repos
      dnf:
        name: "https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm"
        disable_gpg_check: True
        state: present
    
    - name: Install Zabbix Server, Frontend and agent
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-mysql 
        - zabbix-web-mysql 
        - zabbix-apache-conf 
        - zabbix-agent

    - name: Setup Zabbix Php config
      template:
        src: templates/zabbix.conf.j2
        dest: /var/www/html/zabbix.conf.php
        mode: '0644'
      notify: restart apache
    
    - name: Restarting httpd after Zabbix Php configs
      meta: flush_handlers

    - name: Ensure Mariadb is installed
      include: mariadb.yml
    
    - name: Zabbix configuration
      template:
        src: templates/zabbix_server.j2
        dest: /etc/zabbix/zabbix_server.conf
        mode: '0644'
    
    - name: Create Zabbix Directory Log file
      file:
        path: "/var/log/zabbix-server"
        owner: zabbix
        group: zabbix
        mode: '0664'
        state: directory
    
    - name: Create Zabbix Log file
      file:
        path: "/var/log/zabbix-server/zabbix_server.log"
        owner: zabbix
        group: zabbix
        mode: '0664'
        state: touch

    - name: Starting Zabbix server
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - httpd
        - php-fpm


  handlers:
    - name: restart apache
      systemd:
        name: httpd
        state: restarted

    - name: reboot selinux
      command: systemctl reboot

    - name: import zabbix schema
      mysql_db:
        name: zabbix
        state: import
        target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
        login_user: zabbix
        login_password: zabbix

  
    - name: reload firewalld
      command: firewall-cmd --reload
